export const RETRIEVE_LOG = "RETRIEVE_LOG";
export const CREATE_FEED_LOG = "CREATE_FEED_LOG";
export const CREATE_BOWEL_LOG = "CREATE_BOWEL_LOG";
export const UPDATE_LOG = "UPDATE_LOG";
export const DELETE_FEED_LOG = "DELETE_FEED_LOG";
export const DELETE_BOWEL_LOG = "DELETE_BOWEL_LOG";